options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Streamlit container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/streamlit-ui', '-f', 'Dockerfile.streamlit', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/streamlit-ui']
  
  # Deploy to streamline-fe VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      mkdir -p /root/.ssh
      echo "$$SSH_KEY" > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      cat << EOF > /root/.ssh/config
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
      EOF
      chmod 600 /root/.ssh/config
      ssh abvy8498@34.121.73.92 '
        gcloud auth configure-docker && \
        docker pull gcr.io/mlops-project-440315/streamlit-ui && \
        docker stop streamlit-container || true && \
        docker rm streamlit-container || true && \
        docker run -d --name streamlit-container \
          -p 8501:8501 \
          --restart always \
          gcr.io/mlops-project-440315/streamlit-ui
      '
    secretEnv: ['SSH_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/mlops-project-440315/secrets/vm-ssh-key/versions/latest
      env: 'SSH_KEY'