options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Streamlit container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/streamlit-ui', '-f', 'Dockerfile.streamlit', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/streamlit-ui']
  
  # Deploy to streamline-fe VM using gcloud compute ssh
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - streamline-fe
      - --zone=us-central1-c
      - --command=|
          gcloud auth configure-docker && \
          docker pull gcr.io/mlops-project-440315/streamlit-ui && \
          docker stop streamlit-container || true && \
          docker rm streamlit-container || true && \
          docker run -d --name streamlit-container \
            -p 8501:8501 \
            --restart always \
            gcr.io/mlops-project-440315/streamlit-ui