options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Subscriber container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']
  
  # Deploy to mlops-subscriber VM using IAP tunneling
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - mlops-subscriber
      - --zone=us-central1-a
      - --tunnel-through-iap
      - --command="sudo apt-get update && sudo apt-get install -y docker.io && sudo systemctl start docker && sudo usermod -aG docker $USER && sudo gcloud auth configure-docker && sudo docker pull gcr.io/mlops-project-440315/subscriber && sudo docker stop subscriber-container || true && sudo docker rm subscriber-container || true && sudo docker run -d --name subscriber-container -v $(pwd)/fastapi_service:/app/fastapi_service --restart always gcr.io/mlops-project-440315/subscriber"