options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Subscriber container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']
  
  # Deploy to mlops-subscriber VM using gcloud compute ssh
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - mlops-subscriber
      - --zone=us-central1-a
      - --command=|
          gcloud auth configure-docker && \
          docker pull gcr.io/mlops-project-440315/subscriber && \
          docker stop subscriber-container || true && \
          docker rm subscriber-container || true && \
          docker run -d --name subscriber-container \
            --restart always \
            gcr.io/mlops-project-440315/subscriber