options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Subscriber container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']
  
  # Deploy to mlops-subscriber VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      mkdir -p /root/.ssh
      echo "$$SSH_KEY" > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      cat << EOF > /root/.ssh/config
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
      EOF
      chmod 600 /root/.ssh/config
      ssh abvy8498@10.128.0.2 '
        gcloud auth configure-docker && \
        docker pull gcr.io/mlops-project-440315/subscriber && \
        docker stop subscriber-container || true && \
        docker rm subscriber-container || true && \
        docker run -d --name subscriber-container \
          --restart always \
          gcr.io/mlops-project-440315/subscriber
      '
    secretEnv: ['SSH_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/mlops-project-440315/secrets/vm-ssh-key/versions/latest
      env: 'SSH_KEY'