options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Subscriber container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']
  
  # Deploy to mlops-subscriber VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "$$SSH_KEY" > /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh -o StrictHostKeyChecking=no abvy8498@10.128.0.2 '
        gcloud auth configure-docker && \
        docker pull gcr.io/mlops-project-440315/subscriber && \
        docker stop subscriber-container || true && \
        docker rm subscriber-container || true && \
        docker run -d --name subscriber-container \
          -v $(pwd)/fastapi_service:/app/fastapi_service \
          --restart always \
          gcr.io/mlops-project-440315/subscriber
      '
    secretEnv: ['SSH_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/mlops-project-440315/secrets/vm-ssh-key/versions/latest
      env: 'SSH_KEY'