steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "$$SSH_KEY" > /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh -o StrictHostKeyChecking=no abvy8498@10.128.0.2 '
        gcloud auth configure-docker && \
        docker pull gcr.io/mlops-project-440315/subscriber && \
        docker stop subscriber-container || true && \
        docker rm subscriber-container || true && \
        docker run -d --name subscriber-container \
          --restart always \
          gcr.io/mlops-project-440315/subscriber
      '
    secretEnv: ['SSH_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/mlops-project-440315/secrets/vm-ssh-key/versions/latest
      env: 'SSH_KEY'