options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Subscriber container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-project-440315/subscriber', '-f', 'Dockerfile.subscriber', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-project-440315/subscriber']

  # Install Docker and run container on VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud compute ssh mlops-subscriber --zone=us-central1-a --command='
      sudo apt-get update -y && \
      sudo apt-get install -y docker.io && \
      sudo systemctl start docker && \
      sudo gcloud auth configure-docker && \
      sudo docker pull gcr.io/mlops-project-440315/subscriber && \
      sudo docker stop subscriber-container || true && \
      sudo docker rm subscriber-container || true && \
      sudo docker run -d --name subscriber-container --restart always gcr.io/mlops-project-440315/subscriber'