# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the entire project
COPY . /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the subscriber
CMD ["python", "fastapi_service/subscriber.py"]